# -*- coding: utf-8 -*-
"""AI Segments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDNK-7UijUXzrEsvWz-KDA7KbC0B3aOa
"""

import pandas as pd
import numpy as np
from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import IsolationForest

class DataAgent:
    def load_data(self, file_path):
        df = pd.read_csv(file_path)
        # Print columns to debug KeyError
        print("DataFrame columns:", df.columns)
        # It's likely that 'invoice_date' or 'due_date' columns don't exist or are misspelled.
        # Please check the printed columns and adjust the column names below if necessary.
        df['issuedDate'] = pd.to_datetime(df['issuedDate'], format='%d-%m-%Y')
        df['dueDate'] = pd.to_datetime(df['dueDate'], format='%d-%m-%Y')
        return df

data_agent = DataAgent()
df = data_agent.load_data("INVOICES.csv")

print("✅ Data Loaded Successfully")
print(df.head())

class InvoiceValidationAgent:
    def validate(self, df):
        df['is_valid'] = True

        # Negative or zero amount
        df.loc[df['total'] <= 0, 'is_valid'] = False

        # GST validation (18% rule example)
        expected_gst = df['total'] * 0.18
        df.loc[abs(df['tax'] - expected_gst) > 100, 'is_valid'] = False

        return df

validator = InvoiceValidationAgent()
df = validator.validate(df)

class DuplicateDetectionAgent:
    def preprocess(self, df):
        le = LabelEncoder()
        df['vendor_enc'] = le.fit_transform(df['client']) # Changed 'vendor_id' to 'client'
        return df

    def detect_duplicates(self, df):
        df['duplicate_flag'] = 0

        duplicates = df.duplicated(
            subset=['client', 'id_invoice', 'total'], # Changed 'vendor_id' to 'client', 'invoice_number' to 'id_invoice', and 'amount' to 'total'
            keep=False
        )
        df.loc[duplicates, 'duplicate_flag'] = 1
        return df

duplicate_agent = DuplicateDetectionAgent()
df = duplicate_agent.preprocess(df)
df = duplicate_agent.detect_duplicates(df)

class AnomalyDetectionAgent:
    def detect(self, df):
        model = IsolationForest(contamination=0.1, random_state=42)
        df['amount_scaled'] = df['total'] # Changed 'amount' to 'total'
        df['anomaly'] = model.fit_predict(df[['amount_scaled']])
        df['anomaly'] = df['anomaly'].map({1: 0, -1: 1})
        return df

anomaly_agent = AnomalyDetectionAgent()
df = anomaly_agent.detect(df)

class PaymentSchedulingAgent:
    def schedule(self, df):
        today = datetime.today()
        df['days_to_due'] = (df['dueDate'] - today).dt.days # Changed 'due_date' to 'dueDate'

        df['payment_priority'] = np.where(
            (df['days_to_due'] <= 7) &
            (df['anomaly'] == 0) &
            (df['duplicate_flag'] == 0) &
            (df['is_valid'] == True),
            'HIGH',
            'HOLD'
        )
        return df

payment_agent = PaymentSchedulingAgent()
df = payment_agent.schedule(df)

class MonitoringDashboard:
    def summary(self, df):
        summary = {
            "Total Invoices": len(df),
            "Valid Invoices": df['is_valid'].sum(),
            "Duplicate Invoices": df['duplicate_flag'].sum(),
            "Anomalous Invoices": df['anomaly'].sum(),
            "Ready for Payment": (df['payment_priority'] == 'HIGH').sum()
        }
        return summary

dashboard = MonitoringDashboard()
print(dashboard.summary(df))

df.to_csv("processed_invoices_output.csv", index=False)
print("Processed invoice file saved successfully.")

df[['id_invoice','client','total','is_valid','duplicate_flag','anomaly','payment_priority']]

from google.colab import files
files.download("processed_invoices_output.csv")